<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * Contains reset_roles.module.
 */

/**
 * Implements hook_theme().
 */
function reset_roles_theme($existing, $type, $theme, $path) {

  return [
    'reset_roles_form' => [
      'render element' => 'form',
      'template' => 'reset-roles',
    ],
  ];
}

/**
 * Implements hook_help().
 */
function reset_roles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.reset_roles':
      return '<p>' . t('A través de este módulo usted, podrá reiniciar la contraseña de un grupo de usuarios definidos por un rol, mediante el envío de un enlace a una url donde el usuario tendrá la posibilidad de cambiar su contraseña actual. También existe la posibilidad de forzar a el usuario que reciba el correo a que utilice este enlace para cambiar su contraseña en el acto, mediante una expulsión inmediata si se encuentra dentro del sistema drupal y la sobreescritura de su contraseña por una random creada en el momento de la ejecución de este módulo.') . '</p>';
  }
}
